# Маппинг путей: Notion структура → GitHub структура
# Используется при импорте для безопасного сопоставления

mappings:
  # Корневые разделы
  "Вова и Петрова/База знаний/**":
    to: "docs/kb/"
    preserve_structure: true
  
  "Think Tank — компактное ядро/**":
    to: "docs/think-tank/"
  
  "Think Tank — витрина процесса/**":
    to: "docs/think-tank/"
  
  "Навигация (пользовательская)/**":
    to: "docs/nav/"

# Разрешённые зоны записи
allowed_paths:
  - "docs/**"
  - "docs/nav/**"

# Запрещённые зоны (нельзя перезаписывать)
# Обновлено: актуализирован список после последних изменений (2025-11-20)
deny_paths:
  # Скрипты и автоматизация
  - "scripts/**"
  - "scripts/codegpt/**"
  
  # GitHub конфигурация
  - ".github/**"
  
  # Зависимости и конфигурация проекта
  - "package.json"
  - "package-lock.json"
  - "composer.json"
  - "composer.lock"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  
  # Корневые файлы проекта
  - "README.md"
  - "CONTRIBUTING.md"
  - "LICENSE"
  - "SECURITY.md"
  - "CHANGELOG.md"
  - ".gitignore"
  - ".gitattributes"
  
  # Секреты и конфигурация
  - ".env"
  - ".env.*"
  - "codegpt.config.json"
  - "vscode-settings.example.json"
  
  # Системные директории
  - "node_modules/**"
  - "vendor/**"
  - ".cache/**"
  - ".telemetry/**"
  - "tmp/**"
  - "temp/**"
  
  # Автоматически генерируемые файлы
  - "prototype/data/**"
  - "prototype/page/**"
  - "prototype/data/.build-cache.json"
  
  # Критические конфигурационные файлы
  - "docs/.import-map.yaml"
  - ".codegpt/**"
  - "notion-brain/**"
  
  # Тестовые и временные файлы
  - "test-guardrails-v2/**"
  - "lint.log"
  - "STRUCTURE-REPORT.md"

# Правила переименования по slug (если нужно)
slug_overrides:
  # Пример: если Notion экспортирует как "Старое название", а в репо уже "novoe-nazvanie"
  # "Старое название": "novoe-nazvanie"

